Fix for error: Cannot find module ‘./device-config-schema’
Added missing file "device-config-schema.coffee" to "files" property of the package descriptor as reported in https://forum.pimatic.org/topic/2205/add-wemo-switch-device